### ISSUE TITLE
Reader improvement

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/gpmdb-ddi-reader#3]
@Leprevost It would be nice to improve the way we read specific folders to do the update, process and generation. For example, it would be more faster if we are able to pass references by command line of the folder in use. 
  perl ddi-gpmdb-reader.pl -update -folders "001, 003" 
It will allow me to run this in a distributed environment with jobs.

**Comment by Leprevost** [comment]
done!

First I updated the hardcoded directory address for the temp folder with a variable that points to the parameter file.

The actual updates now gives you the option to use the directories from the parameter file or from the command line option, for example:

# using the directories from parameter file
perl ddi-gpmdb-reader.pl -update param
or
perl ddi-gpmdb-reader.pl -update

# overwriting the parameter file (pass folders separated by comma)
perl ddi-gpmdb-reader.pl -update 003,066,112 

This pattern will work with all 3 commands.

**Comment by ypriverol** [comment]
@Leprevost I will tested

**Comment by ypriverol** [comment]
+1
